/* Ruleta de demostración. Todas las recompensas tienen una probabilidad positiva. */
var PRIZES=[{label:'$3.000 OFF',short:'$3.000',weight:5900,discount:0,monto:3000},{label:'$6.000 OFF',short:'$6.000',weight:2500,discount:0,monto:6000},{label:'15% OFF',short:'15%',weight:1000,discount:15},{label:'25% OFF',short:'25%',weight:350,discount:25},{label:'Envío gratis',short:'ENVÍO',weight:150,discount:0,envio:true},{label:'Mystery Box',short:'MYSTERY',weight:100,discount:0,mystery:true}];
var spinBusy=false,spinTurn=0,spinTimeout=null;
var spinRecord=loadSpin();
function loadSpin(){try{var v=JSON.parse(localStorage.getItem('laonce-ruleta-demo')||'null');return v&&Number.isInteger(v.prize)&&v.prize>=0&&v.prize<6&&Number.isFinite(v.at)&&v.at<=Date.now()&&typeof v.code==='string'&&/^(DEMO|ONCE)-[A-Z0-9-]+$/.test(v.code)?v:null}catch(e){return null}}
function activeSpin(){return spinRecord&&Date.now()-spinRecord.at<SPIN_INTERVAL?spinRecord:null}
function choosePrize(n){var sum=0;for(var i=0;i<PRIZES.length;i++){sum+=PRIZES[i].weight;if(n<sum)return i}throw Error('Sorteo fuera de rango')}
function randomTicket(){var a=new Uint32Array(1),max=Math.floor(4294967296/10000)*10000;do{crypto.getRandomValues(a)}while(a[0]>=max);return a[0]%10000}
function prizeTicket(){var r=activeSpin();if(!r||spinBusy)return '';var p=PRIZES[r.prize];if(r.used)return '<div class="prize-ticket" role="status"><span class="eyebrow">Tu premio</span><h2>'+p.label+'</h2><p>Ya lo usaste en tu último pedido. Volvés a girar cuando se cumplan los 3 días.</p></div>';return '<div class="prize-ticket" role="status"><span class="eyebrow">Tu premio</span><h2>'+p.label+'</h2><p>'+(p.mystery?'Una camiseta sorpresa de regalo, elegida por nosotros. Se suma a tu próximo pedido o la pedís sola por WhatsApp (envío aparte).':p.envio?'Para tu próximo pedido con envío a domicilio.':p.monto?'Se descuenta de tu compra de camisetas en stock.':p.discount===100?'Una camiseta en stock gratis, la de menor precio de tu carrito. Envío aparte.':'Sobre una camiseta en stock, la de menor precio de tu carrito.')+(p.mystery?'':' Se aplica solo al finalizar la compra.')+'</p>'+(p.mystery&&waNumber()?'<a class="btn btn-wa mb-claim" target="_blank" rel="noopener" href="https://wa.me/'+waNumber()+'?text='+encodeURIComponent('Hola! Gané una Mystery Box en la ruleta. Código '+r.code)+'">Pedirla por WhatsApp</a>':'')+'<p>Vence '+new Date(r.at+SPIN_INTERVAL).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})+''+(p.mystery?'.':p.envio||p.monto?'. Se suma al descuento por transferencia.':'. No se suma al descuento por transferencia: te queda el mayor.')+'</p></div>'}
function gameRules(){return '<details class="game-rules"><summary>Premios, probabilidades y cómo funciona</summary><div class="odds">'+PRIZES.map(function(p){return '<div><strong>'+p.short+'</strong><span>'+(p.weight/100).toLocaleString('es-AR')+'% de probabilidad</span></div>'}).join('')+'</div><div class="rules-copy"><p>Las porciones de la rueda son ilustrativas: las probabilidades son las indicadas arriba y suman 100%. Todos los premios pueden salir.</p><p>Podés girar una vez cada 3 días. Tu premio dura 3 días desde que girás y queda guardado aunque cierres la página.</p><p>Los premios de $3.000 y $6.000 se descuentan de una compra con camisetas en stock y se suman al descuento por transferencia. Los porcentajes se aplican sobre una camiseta en stock (la de menor precio del carrito), sin compra mínima; personalización aparte, y no se acumulan con el descuento por transferencia: se aplica el mayor beneficio. La Mystery Box es una camiseta sorpresa de regalo elegida por nosotros: se suma a tu próximo pedido o la pedís sola por WhatsApp, sin compra mínima (envío aparte). Los encargos no participan. El envío gratis vale para un pedido con envío a domicilio, incluidos los encargos, y sí se suma al descuento por transferencia.</p><p>El premio queda guardado en este navegador y se aplica automáticamente en el carrito y al finalizar la compra. Lo validamos con su código cuando coordinamos el pedido por WhatsApp. Un premio por pedido.</p></div></details>'}
/* ---------- Ruleta estilo casino ---------- */
/* Casilleros de la rueda (índice del premio en PRIZES). El 0 verde es la Mystery Box, como el cero del casino.
   La cantidad de casilleros es decorativa: la probabilidad real de cada premio es la de PRIZES. */
var POCKETS=[5,0,2,1,0,3,1,0,4,2,0,1,3,0,1,2,0,4],POCKET_DEG=360/POCKETS.length;
var BALL_TRACK=178,BALL_POCKET=111;
function cwPolar(r,a){var t=(a-90)*Math.PI/180;return [200+r*Math.cos(t),200+r*Math.sin(t)]}
function cwWedge(r1,r2,a1,a2){var p1=cwPolar(r2,a1),p2=cwPolar(r2,a2),p3=cwPolar(r1,a2),p4=cwPolar(r1,a1),f=function(n){return n.toFixed(2)};return 'M'+f(p1[0])+' '+f(p1[1])+'A'+r2+' '+r2+' 0 0 1 '+f(p2[0])+' '+f(p2[1])+'L'+f(p3[0])+' '+f(p3[1])+'A'+r1+' '+r1+' 0 0 0 '+f(p4[0])+' '+f(p4[1])+'Z'}
function pocketColor(k){return k===0?'#0f7a3d':(k%2?'#b3141c':'#151515')}
function pocketOf(r){if(!r)return 0;if(Number.isInteger(r.pocket)&&POCKETS[r.pocket]===r.prize)return r.pocket;return POCKETS.indexOf(r.prize)}
function restRotation(r){return r?((360-pocketOf(r)*POCKET_DEG)%360):0}
function ballXY(angle,radius){var p=cwPolar(radius,angle);return 'cx="'+p[0].toFixed(2)+'" cy="'+p[1].toFixed(2)+'"'}
function wheelLabel(p){return p.mystery?['MYSTERY','BOX']:p.envio?['ENVÍO','GRATIS']:[p.short,'']}
function casinoWheel(rot,ballAngle,ballRadius){
  var defs='<defs><radialGradient id="cwWood" cx="50%" cy="42%" r="60%"><stop offset="0" stop-color="#8a4c25"/><stop offset=".62" stop-color="#5b2d12"/><stop offset="1" stop-color="#2a1306"/></radialGradient>'+
    '<linearGradient id="cwGold" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#fff0b0"/><stop offset=".28" stop-color="#e8bd52"/><stop offset=".62" stop-color="#a87418"/><stop offset=".82" stop-color="#e6c060"/><stop offset="1" stop-color="#8d5f12"/></linearGradient>'+
    '<radialGradient id="cwTrack" cx="50%" cy="50%" r="50%"><stop offset=".84" stop-color="#7a4a14"/><stop offset=".9" stop-color="#d9ab45"/><stop offset=".95" stop-color="#f3d77e"/><stop offset="1" stop-color="#9c6a16"/></radialGradient>'+
    '<radialGradient id="cwCone" cx="50%" cy="45%" r="55%"><stop offset="0" stop-color="#b07a4a"/><stop offset=".55" stop-color="#7a4b26"/><stop offset="1" stop-color="#3f2410"/></radialGradient>'+
    '<radialGradient id="cwBall" cx="35%" cy="32%" r="70%"><stop offset="0" stop-color="#fff"/><stop offset=".55" stop-color="#e9eaec"/><stop offset="1" stop-color="#9ea3aa"/></radialGradient>'+
    '<radialGradient id="cwShade" cx="50%" cy="50%" r="50%"><stop offset=".7" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity=".45"/></radialGradient></defs>';
  var s='<circle cx="200" cy="200" r="199" fill="url(#cwWood)"/><circle cx="200" cy="200" r="198" fill="none" stroke="#1a0b03" stroke-width="2"/>'+
    '<circle cx="200" cy="200" r="190" fill="url(#cwTrack)"/><circle cx="200" cy="200" r="168.5" fill="none" stroke="#5c3a0c" stroke-width="2"/>';
  for(var d=0;d<8;d++){var c=cwPolar(181,d*45+22.5);s+='<rect x="'+(c[0]-4.5).toFixed(2)+'" y="'+(c[1]-4.5).toFixed(2)+'" width="9" height="9" transform="rotate('+(d*45+67.5)+' '+c[0].toFixed(2)+' '+c[1].toFixed(2)+')" fill="url(#cwGold)" stroke="#6b4510" stroke-width=".8"/>'}
  var g='<circle cx="200" cy="200" r="167" fill="url(#cwGold)"/>';
  POCKETS.forEach(function(pi,k){var a=k*POCKET_DEG,a1=a-POCKET_DEG/2,a2=a+POCKET_DEG/2,col=pocketColor(k);
    g+='<path d="'+cwWedge(120,164,a1,a2)+'" fill="'+col+'"/><path d="'+cwWedge(100,120,a1,a2)+'" fill="'+col+'"/><path d="'+cwWedge(100,120,a1,a2)+'" fill="#000" opacity=".28"/>';
    var L=wheelLabel(PRIZES[pi]),t1=cwPolar(L[1]?150:143,a),t2=cwPolar(131,a),long=L[0].length>4;
    g+='<text x="'+t1[0].toFixed(2)+'" y="'+t1[1].toFixed(2)+'" transform="rotate('+a+' '+t1[0].toFixed(2)+' '+t1[1].toFixed(2)+')" class="cw-num"'+(long?' textLength="'+(L[0].length>6?40:L[0].length>5?39:35)+'" lengthAdjust="spacingAndGlyphs"':' textLength="34" lengthAdjust="spacingAndGlyphs"')+' font-size="'+(L[0].length>6?17:L[0].length>5?20:long?20:23)+'">'+esc(L[0])+'</text>';
    if(L[1])g+='<text x="'+t2[0].toFixed(2)+'" y="'+t2[1].toFixed(2)+'" transform="rotate('+a+' '+t2[0].toFixed(2)+' '+t2[1].toFixed(2)+')" class="cw-sub" textLength="'+(L[1].length>3?34:21)+'" lengthAdjust="spacingAndGlyphs">'+L[1]+'</text>'});
  POCKETS.forEach(function(_,k){var a=k*POCKET_DEG-POCKET_DEG/2,o=cwPolar(164,a),i=cwPolar(100,a);g+='<line x1="'+o[0].toFixed(2)+'" y1="'+o[1].toFixed(2)+'" x2="'+i[0].toFixed(2)+'" y2="'+i[1].toFixed(2)+'" stroke="url(#cwGold)" stroke-width="1.6"/>'});
  g+='<circle cx="200" cy="200" r="120" fill="none" stroke="#e2b54c" stroke-width="2"/><circle cx="200" cy="200" r="100" fill="url(#cwCone)" stroke="#d6a640" stroke-width="2.5"/>';
  for(var q=0;q<16;q++){var o2=cwPolar(98,q*22.5),i2=cwPolar(46,q*22.5);g+='<line x1="'+o2[0].toFixed(2)+'" y1="'+o2[1].toFixed(2)+'" x2="'+i2[0].toFixed(2)+'" y2="'+i2[1].toFixed(2)+'" stroke="#2c170a" stroke-opacity=".35" stroke-width="1"/>'}
  for(var arm=0;arm<4;arm++){var e=cwPolar(80,arm*90+45);g+='<line x1="200" y1="200" x2="'+e[0].toFixed(2)+'" y2="'+e[1].toFixed(2)+'" stroke="url(#cwGold)" stroke-width="7" stroke-linecap="round"/><circle cx="'+e[0].toFixed(2)+'" cy="'+e[1].toFixed(2)+'" r="7" fill="url(#cwGold)" stroke="#6b4510" stroke-width="1"/>'}
  var logo=String((data.config&&(data.config.ruletaLogo||data.config.logo))||'');
  var hub='<circle cx="200" cy="200" r="47" fill="url(#cwGold)" stroke="#6b4510" stroke-width="1.5"/><circle cx="200" cy="200" r="40" fill="#0f2a5c"/>'+
    (/^(data:image\/|https:\/\/|assets\/)/.test(logo)?'<image href="'+esc(logo)+'" x="154" y="154" width="92" height="92" preserveAspectRatio="xMidYMid meet"/>':'<text x="200" y="215" class="cw-logo">11</text>');
  return '<svg class="cw-svg" viewBox="0 0 400 400" role="img" aria-label="Ruleta de premios">'+defs+s+'<g class="cw-rotor" transform="rotate('+rot.toFixed(3)+' 200 200)">'+g+'</g><circle cx="200" cy="200" r="190" fill="url(#cwShade)" pointer-events="none"/>'+hub+'<circle class="cw-ball" r="6.5" '+ballXY(ballAngle,ballRadius)+' fill="url(#cwBall)" stroke="#6d737b" stroke-width=".6"/></svg>';
}
function renderGame(){clearInterval(timer);var r=activeSpin();app.innerHTML=header()+'<main class="wrap club-main"><section class="club-surface casino"><div class="club-topline"><span>LA ONCE</span><span class="club-demo">CADA 3 DÍAS</span></div><div class="club-layout"><div class="club-copy"><span class="eyebrow">El próximo gol puede ser tuyo</span><h1>Una vuelta.<br><em>Una ilusión.</em></h1><p>De $3.000 de descuento a una Mystery Box. Dale un giro a la suerte.</p>'+prizeTicket()+'<button class="spin-button" id="spinWheel" '+(spinBusy||r?'disabled':'')+'>'+(spinBusy?'Girando…':r?nextSpinLabel():'Girar la ruleta ↗')+'</button>'+(r&&!r.used?'<button class="linkish" style="display:block;margin:14px auto 0" data-nav="stock">Usar mi premio en camisetas en stock →</button>':'')+'<button class="game-sound" id="toggleGameSound" aria-pressed="'+soundEnabled+'">'+(soundEnabled?'♫ Sonido activado':'♫ Sonido desactivado')+'</button><p class="spin-small">Un giro cada 3 días. Participación gratuita. El premio se aplica solo en tu carrito.</p></div><div class="wheel-area casino-wheel">'+casinoWheel(spinBusy?spinTurn:restRotation(r),r||spinBusy?(spinBusy?spinBallA:0):0,r?BALL_POCKET:(spinBusy?spinBallR:BALL_TRACK))+'</div></div><div class="club-bottom"><span>6 premios · Todas las chances a la vista</span><span>Sin compra obligatoria</span></div></section>'+gameRules()+'</main>'+footer()+'<dialog id="dlg"></dialog><dialog id="bagDlg" class="drawer"></dialog><div class="toast" id="toast" role="status"></div>';app.querySelector('#spinWheel').onclick=spinWheel;var b=app.querySelector('#copyPrize');if(b)b.onclick=function(){copyText(activeSpin().code,b)};app.querySelector('#toggleGameSound').onclick=toggleSound;armGameClock()}
async function copyText(t,b){try{await navigator.clipboard.writeText(t);b.textContent='Copiado'}catch(e){b.textContent='Seleccioná el código para copiarlo'}}
function prizeCalc(){var r=activeSpin();if(!r||r.used)return null;var P=PRIZES[r.prize];if(P.envio)return {r:r,P:P,disc:0,prod:null,envio:true};if(P.mystery)return {r:r,P:P,disc:0,prod:null,mystery:true};var st=cart.map(function(l){return byId(l.id)}).filter(function(p){return p&&!isPre(p)});if(!st.length)return {r:r,P:P,disc:0,prod:null};var p=st.reduce(function(a,b){return b.precio<a.precio?b:a});return P.monto?{r:r,P:P,disc:Math.min(P.monto,p.precio),prod:p,stack:true}:{r:r,P:P,disc:Math.round(p.precio*P.discount/100),prod:p}}
function demoDiscount(){var z=prizeCalc();return z?z.disc:0}
function prizeLabel(z){return z.P.discount===100?'Camiseta gratis':z.P.label}
function prizeLeft(r){var m=Math.max(1,Math.ceil((r.at+SPIN_INTERVAL-Date.now())/60000)),h=Math.floor(m/60);return (h?h+' h ':'')+(m%60)+' min'}
function checkoutGame(){var T=coTotals(),z=T.pz;if(!z)return '';var msg;if(z.mystery)msg='Sumamos tu Mystery Box de regalo a este pedido: una camiseta sorpresa elegida por nosotros.';else if(z.envio)msg=T.envioPrize?'Tu envío a domicilio es gratis. Se suma al descuento por transferencia.':co.entrega==='envio'?'Tu pedido ya tiene envío gratis, así que tu premio queda guardado hasta que venza.':'Tu premio es envío gratis: se usa si elegís envío a domicilio.';else if(!z.disc)msg='Tu premio ('+esc(z.P.label)+') vale para compras con camisetas en stock. Los encargos no participan.';else if(z.stack)msg='Aplicamos '+esc(z.P.label)+' en tu compra'+(T.td?' y se suma al '+T.d+'% por transferencia.':'.');else if(T.usePrize)msg='Aplicamos '+(z.P.discount===100?'una camiseta gratis':esc(z.P.label))+' en '+esc(z.prod.club)+(T.td?'. No se suma al '+T.d+'% por transferencia: te dejamos el mayor beneficio.':'.');else msg='Con transferencia ya tenés '+T.d+'% en todo el pedido, que es igual o mejor que tu premio ('+esc(z.P.label)+'). Te aplicamos la transferencia y tu premio queda guardado hasta que venza.';return '<div class="game-checkout"><b>Premio de la ruleta</b><p>'+msg+'</p><p class="hint">Vence en '+prizeLeft(z.r)+'</p></div>'}
function prizeBar(){if(view==='game')return '';var r=activeSpin();if(!r||r.used)return '';var P=PRIZES[r.prize];return '<button class="prize-bar" id="prizeBar" type="button"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 11h16v9H4zM3 7h18v4H3zM12 7v13M12 7c-1.5-3.5-6-3.5-5 0 .4 1.2 2.8 1 5 0zm0 0c1.5-3.5 6-3.5 5 0-.4 1.2-2.8 1-5 0z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg><span class="pb-txt">Ganaste <b>'+(P.mystery?'una Mystery Box':P.envio?'envío gratis':esc(P.label))+'</b> en la ruleta<span class="pb-sep"> · </span><span class="pb-when">vence en <b class="pb-time">'+prizeLeft(r)+'</b></span></span><span class="pb-go">Usar ›</span></button>'}
setInterval(function(){var el=document.querySelector('.pb-time');if(!el)return;var r=activeSpin();if(!r){render();return}el.textContent=prizeLeft(r)},30000);

/* Catálogo seleccionado: importación local revisable, no sincronización remota. */
var importDraft=[];
function supplierPanel(){return '<section class="admin-import"><h3>Catálogo por pedido</h3><p>Primera selección consultada el 29/09/2026. Fichas públicas de GRKITS, ASJSY y SSDAYS; no es disponibilidad en tiempo real. Los precios en pesos son de prueba. Descargá la copia HTML para conservar cambios.</p><p>Para ampliar: pegá un JSON con id, club, titulo, categoria, epoca, precio, fuente, foto y tallesPedido. Cada importación se revisa antes de incorporarla. Solo camisetas; sin shorts, conjuntos ni accesorios.</p><textarea id="importJson" aria-label="Catálogo JSON de camisetas" placeholder="Pegá acá el catálogo JSON seleccionado"></textarea><button class="btn btn-ghost" id="previewImport">Revisar importación</button><button class="btn btn-ghost" id="exportCatalog">Exportar catálogo por pedido</button><div id="importPreview" role="status"></div></section>'}
function cleanImported(rows){if(!Array.isArray(rows)||!rows.length||rows.length>500)throw Error('Usá una lista de entre 1 y 500 camisetas.');var seen=new Set();return rows.map(function(p,i){if(!p||typeof p!=='object')throw Error('Fila '+(i+1)+': formato inválido.');var id=String(p.id||'').trim();if(!/^[a-zA-Z0-9_-]{1,70}$/.test(id)||seen.has(id))throw Error('Fila '+(i+1)+': ID inválido o repetido.');seen.add(id);if(data.productos.some(function(x){return x.id===id&&!isPre(x)}))throw Error(id+': ese ID pertenece al stock local.');if(!p.club||!p.titulo||!CATS.includes(p.categoria)||!EPOCAS.includes(p.epoca))throw Error(id+': revisá club, título, categoría y época.');if(/\b(shorts?|pants|tracksuit|socks?|conjunto|pantal[oó]n|medias|nba|rugby)\b/i.test(p.titulo))throw Error(id+': la selección admite únicamente camisetas de fútbol.');if(!Number.isFinite(p.precio)||p.precio<=0)throw Error(id+': falta un precio positivo en pesos.');var url;try{url=new URL(p.fuente)}catch(e){throw Error(id+': falta el enlace de origen.')}var host=url.hostname.replace(/^www\./,'');if(url.protocol!=='https:'||url.username||url.password||!['grkits7.com','asjsy.com','ssdays2.com'].includes(host))throw Error(id+': usá un enlace HTTPS de uno de tus tres proveedores.');var sizes=Array.isArray(p.tallesPedido)?p.tallesPedido:[];if(!sizes.length||sizes.some(function(s){return !SIZES.includes(s)}))throw Error(id+': indicá tallesPedido con S, M, L, XL o XXL.');var photo=String(p.foto||'');if(photo&&!/^https:\/\//i.test(photo)&&!/^data:image\/(png|jpeg|webp);base64,[a-zA-Z0-9+/=]+$/.test(photo))throw Error(id+': formato de foto no admitido.');return {id:id,club:String(p.club).slice(0,100),titulo:String(p.titulo).slice(0,180),categoria:p.categoria,epoca:p.epoca,precio:Math.round(p.precio),precioAnterior:0,fuente:url.href,proveedor:host,fechaConsulta:p.fechaConsulta||new Date().toISOString().slice(0,10),foto:photo||null,tallesPedido:[...new Set(sizes)],stock:{S:0,M:0,L:0,XL:0,XXL:0},modalidad:'pedido',activo:p.activo!==false,patron:{tipo:'liso',c1:'#ddd',c2:'#aaa'},nuevo:false,destacado:false}})}
function previewImport(){var box=document.getElementById('importPreview');try{importDraft=cleanImported(JSON.parse(document.getElementById('importJson').value));box.innerHTML='<p>'+importDraft.length+' camisetas válidas. Elegí cuáles incorporar; los IDs existentes se actualizan.</p>'+importDraft.map(function(p,i){return '<label style="display:block;margin:8px 0"><input type="checkbox" data-import-row="'+i+'" checked> '+esc(p.club+' · '+p.titulo)+' · '+money(p.precio)+'</label>'}).join('')+'<button class="btn btn-ink" id="commitImport">Importar seleccionadas</button>'}catch(e){importDraft=[];box.innerHTML='<p class="import-error">'+esc(e.message)+'</p>'}}
function commitImport(){var selected=[...app.querySelectorAll('[data-import-row]:checked')].map(function(el){return importDraft[+el.dataset.importRow]});if(!selected.length){toast('Seleccioná al menos una camiseta');return}selected.forEach(function(p){var i=data.productos.findIndex(function(x){return x.id===p.id});if(i<0)data.productos.push(p);else data.productos[i]=p});dirty=true;adminMsg={kind:'info',text:selected.length+' camisetas incorporadas. Descargá la copia HTML para guardar.'};importDraft=[];renderAdmin()}
function exportCatalog(){var rows=data.productos.filter(isPre),blob=new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='La-ONCE-catalogo-por-pedido.json';a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000)}

var SPIN_INTERVAL=3*24*60*60*1000;
var gameClock=null,celebrationFrame=null,spinFrame=null,audioContext=null;
var soundEnabled=(function(){try{return localStorage.getItem('laonce-sonido')!=='off'}catch(e){return true}})();
function nextSpinLabel(){var r=activeSpin();if(!r)return 'Girar la ruleta ↗';var minutes=Math.max(1,Math.ceil((r.at+SPIN_INTERVAL-Date.now())/60000)),hours=Math.floor(minutes/60);return 'Volvés a girar en '+(hours?hours+' h ':'')+(minutes%60)+' min'}
function armGameClock(){clearTimeout(gameClock);if(activeSpin()&&!spinBusy)gameClock=setTimeout(function(){if(view==='game')renderGame()},Math.min(60000,Math.max(100,spinRecord.at+SPIN_INTERVAL-Date.now()+50)))}
function prepareSound(){if(!soundEnabled)return;try{var Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audioContext=audioContext||new Audio();if(audioContext.state==='suspended')audioContext.resume().catch(function(){})}catch(e){}}
function tone(frequency,start,length,volume,type){if(!soundEnabled||!audioContext||audioContext.state!=='running')return;try{var oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime+start;oscillator.type=type||'sine';oscillator.frequency.setValueAtTime(frequency,t);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(volume,t+.012);gain.gain.exponentialRampToValueAtTime(.0001,t+length);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(t);oscillator.stop(t+length+.03)}catch(e){}}
function victorySound(jackpot){if(document.hidden||view!=='game')return;[523.25,659.25,783.99,jackpot?1046.5:880].forEach(function(f,i){tone(f,i*.105,.4,.07,'triangle')});tone(261.63,.31,.65,.05);tone(523.25,.42,.55,.05)}
function toggleSound(){soundEnabled=!soundEnabled;try{localStorage.setItem('laonce-sonido',soundEnabled?'on':'off')}catch(e){}if(soundEnabled){prepareSound();tone(659,0,.16,.04)}var b=document.getElementById('toggleGameSound');if(b){b.textContent=soundEnabled?'♫ Sonido activado':'♫ Sonido desactivado';b.setAttribute('aria-pressed',String(soundEnabled))}}
function burstConfetti(jackpot){if(matchMedia('(prefers-reduced-motion: reduce)').matches||document.hidden)return;var old=document.getElementById('prizeConfetti');if(old)old.remove();cancelAnimationFrame(celebrationFrame);var cv=document.createElement('canvas');cv.id='prizeConfetti';cv.setAttribute('aria-hidden','true');document.body.appendChild(cv);var w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio||1,2);cv.width=w*dpr;cv.height=h*dpr;var ctx=cv.getContext('2d');if(!ctx){cv.remove();return}ctx.scale(dpr,dpr);var colors=['#eabc4e','#f3e8ce','#3c918a','#69b9ec','#ec7962'],particles=[];for(var i=0;i<(jackpot?190:120);i++){var side=i%2?1:-1;particles.push({x:side===1?w:0,y:h*.65,vx:-side*(100+Math.random()*520),vy:-260-Math.random()*600,r:Math.random()*6.28,vr:(Math.random()-.5)*12,size:5+Math.random()*7,color:colors[i%colors.length]})}var begin=performance.now(),last=begin;function frame(now){var dt=Math.min((now-last)/1000,.04),age=(now-begin)/1000;last=now;if(age>3.8||view!=='game'||document.hidden){cv.remove();return}ctx.clearRect(0,0,w,h);ctx.globalAlpha=Math.min(1,(3.8-age)/.8);particles.forEach(function(p){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=440*dt;p.vx*=Math.pow(.96,dt*60);p.r+=p.vr*dt;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillStyle=p.color;ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size*.5);ctx.restore()});celebrationFrame=requestAnimationFrame(frame)}celebrationFrame=requestAnimationFrame(frame)}
function celebratePrize(index){var surface=document.querySelector('.club-surface'),ticket=document.querySelector('.prize-ticket'),area=document.querySelector('.wheel-area');if(surface)surface.classList.add('celebrating');if(index===5&&surface)surface.classList.add('jackpot');if(ticket){ticket.classList.add('prize-reveal');if(innerWidth<=720)ticket.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'})}if(area)area.classList.add('winner');burstConfetti(index===5);victorySound(index===5)}
var spinBallA=0,spinBallR=BALL_TRACK;
function spinWheel(){if(spinBusy||activeSpin())return;prepareSound();var index=choosePrize(randomTicket()),opts=[];POCKETS.forEach(function(p,k){if(p===index)opts.push(k)});var a=new Uint32Array(1);crypto.getRandomValues(a);var pocket=opts[a[0]%opts.length];
  spinRecord={prize:index,pocket:pocket,at:Date.now(),code:'ONCE-'+Date.now().toString(36).toUpperCase()};try{localStorage.setItem('laonce-ruleta-demo',JSON.stringify(spinRecord))}catch(e){}
  spinBusy=true;spinTurn=0;spinBallA=0;spinBallR=BALL_TRACK;var btn=app.querySelector('#spinWheel');btn.disabled=true;btn.textContent='Girando…';clearTimeout(gameClock);cancelAnimationFrame(spinFrame);
  var reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,duration=reduced?100:6200,start=performance.now(),from=0,rest=(360-pocket*POCKET_DEG)%360,target=360*4+rest,lastPocket=-1,ballTurns=5;
  var area=app.querySelector('.casino-wheel');if(area){area.classList.add('spinning');if(innerWidth<=720){var rr=area.getBoundingClientRect();if(rr.top<0||rr.bottom>innerHeight)area.scrollIntoView({behavior:reduced?'instant':'smooth',block:'center'})}}
  function easeOut(t,p){return 1-Math.pow(1-t,p)}
  function frame(now){var t=Math.min(1,(now-start)/duration);spinTurn=from+target*easeOut(t,3.2);
    var free=-360*ballTurns*(1-easeOut(t,2.4)),pocketAbs=pocket*POCKET_DEG+spinTurn,drop=Math.min(1,Math.max(0,(t-.62)/.2)),lock=Math.min(1,Math.max(0,(t-.72)/.16));
    var target2=pocketAbs+360*Math.round((free-pocketAbs)/360);spinBallA=free+(target2-free)*lock*lock*(3-2*lock);
    var bounce=drop>0&&drop<1?Math.sin(drop*Math.PI*3)*(1-drop)*9:0;spinBallR=BALL_TRACK+(BALL_POCKET-BALL_TRACK)*(drop*drop*(3-2*drop))+bounce;
    var svg=app.querySelector('.cw-svg');
    if(svg&&view==='game'){svg.querySelector('.cw-rotor').setAttribute('transform','rotate('+spinTurn.toFixed(3)+' 200 200)');var ball=svg.querySelector('.cw-ball'),bp=cwPolar(spinBallR,spinBallA);ball.setAttribute('cx',bp[0].toFixed(2));ball.setAttribute('cy',bp[1].toFixed(2));
      var under=Math.round((((spinBallA-spinTurn)%360)+360)%360/POCKET_DEG)%POCKETS.length;if(under!==lastPocket&&!reduced&&!document.hidden){lastPocket=under;tone(drop>0?1200:900,0,.03,drop>0?.02:.012,'triangle')}}
    if(t<1){spinFrame=requestAnimationFrame(frame);return}
    spinBusy=false;spinFrame=null;if(view==='game'){renderGame();celebratePrize(index)}}
  spinFrame=requestAnimationFrame(frame)}
