/* Ruleta de demostración. Todas las recompensas tienen una probabilidad positiva. */
var PRIZES=[{label:'5% OFF',short:'5%',weight:5900,discount:5},{label:'10% OFF',short:'10%',weight:2500,discount:10},{label:'15% OFF',short:'15%',weight:1000,discount:15},{label:'25% OFF',short:'25%',weight:350,discount:25},{label:'50% OFF',short:'50%',weight:150,discount:50},{label:'Una camiseta gratis',short:'CAMISETA',weight:100,discount:100}];
var spinBusy=false,spinTurn=0,spinTimeout=null;
var spinRecord=loadSpin();
function loadSpin(){try{var v=JSON.parse(localStorage.getItem('laonce-ruleta-demo')||'null');return v&&Number.isInteger(v.prize)&&v.prize>=0&&v.prize<6&&Number.isFinite(v.at)&&v.at<=Date.now()&&typeof v.code==='string'&&/^DEMO-[A-Z0-9-]+$/.test(v.code)?v:null}catch(e){return null}}
function activeSpin(){return spinRecord&&Date.now()-spinRecord.at<SPIN_INTERVAL?spinRecord:null}
function choosePrize(n){var sum=0;for(var i=0;i<PRIZES.length;i++){sum+=PRIZES[i].weight;if(n<sum)return i}throw Error('Sorteo fuera de rango')}
function randomTicket(){var a=new Uint32Array(1),max=Math.floor(4294967296/10000)*10000;do{crypto.getRandomValues(a)}while(a[0]>=max);return a[0]%10000}
function prizeTicket(){var r=activeSpin();if(!r||spinBusy)return '';var p=PRIZES[r.prize];return '<div class="prize-ticket" role="status"><span class="eyebrow">Tu resultado de prueba</span><h2>'+p.label+'</h2><p>'+(p.discount===100?'Una camiseta en stock, sin compra mínima. Envío aparte.':'Descuento sobre una camiseta en stock, la de menor precio del carrito.')+'</p><span class="coupon-code">'+esc(r.code)+'</span><button id="copyPrize">Copiar</button><p>Vence '+new Date(r.at+SPIN_INTERVAL).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})+'. Código de demostración, sin valor de canje.</p></div>'}
function gameRules(){return '<details class="game-rules"><summary>Premios, probabilidades y cómo funciona</summary><div class="odds">'+PRIZES.map(function(p){return '<div><strong>'+p.short+'</strong><span>'+(p.weight/100).toLocaleString('es-AR')+'% de probabilidad</span></div>'}).join('')+'</div><div class="rules-copy"><p>Las porciones de la rueda son ilustrativas: las probabilidades son las indicadas arriba y suman 100%. Todos los premios pueden salir.</p><p>Un giro de prueba cada 3 días (72 horas) en este navegador. El resultado se guarda al girar, aunque cierres la pestaña. El código dura 72 horas.</p><p>Propuesta de promoción: un premio sobre una camiseta en stock (la de menor precio del carrito), sin compra mínima; envío y personalización aparte. No se acumula con el descuento por transferencia: se aplica el mayor beneficio al total del pedido. Los encargos no participan.</p><p><b>Esta es una demostración.</b> Los códigos no se pueden canjear. La promoción real todavía no está activa.</p></div></details>'}
function renderGame(){clearInterval(timer);var r=activeSpin();app.innerHTML=header()+'<main class="wrap club-main"><section class="club-surface"><div class="club-topline"><span>LA ONCE / EL RECREO</span><span class="club-demo">MODO DEMO</span></div><div class="club-layout"><div class="club-copy"><span class="eyebrow">El próximo gol puede ser tuyo</span><h1>Una vuelta.<br><em>Una ilusión.</em></h1><p>Del 5% de descuento a una camiseta gratis. Dale un giro a la suerte.</p>'+prizeTicket()+'<button class="spin-button" id="spinWheel" '+(spinBusy||r?'disabled':'')+'>'+(spinBusy?'Girando…':r?nextSpinLabel():'Girar la ruleta ↗')+'</button>'+(r?'<button class="linkish" style="display:block;margin:14px auto 0" data-nav="stock">Ver camisetas en stock →</button>':'')+'<button class="game-sound" id="toggleGameSound" aria-pressed="'+soundEnabled+'">'+(soundEnabled?'♫ Sonido activado':'♫ Sonido desactivado')+'</button><p class="spin-small">Un giro cada 3 días. Participación gratuita. Probá el juego: los premios de esta versión son de demostración.</p></div><div class="wheel-area"><span class="wheel-pointer" aria-hidden="true"></span><div class="wheel-rim"><div class="wheel-disc" aria-hidden="true" style="transform:rotate('+(spinBusy?spinTurn:r?-r.prize*60:0)+'deg)">'+PRIZES.map(function(p,i){return '<div class="wheel-label" style="--angle:'+(i*60)+'deg">'+p.short+'<small>'+(i===5?'GRATIS':'DESCUENTO')+'</small></div>'}).join('')+'</div><span class="wheel-hub" aria-hidden="true">11</span></div></div></div><div class="club-bottom"><span>6 premios · Todas las chances a la vista</span><span>Sin compra obligatoria</span></div></section>'+gameRules()+'</main>'+footer()+'<dialog id="dlg"></dialog><dialog id="bagDlg" class="drawer"></dialog><div class="toast" id="toast" role="status"></div>';app.querySelector('#spinWheel').onclick=spinWheel;var b=app.querySelector('#copyPrize');if(b)b.onclick=function(){copyText(activeSpin().code,b)};app.querySelector('#toggleGameSound').onclick=toggleSound;armGameClock()}
async function copyText(t,b){try{await navigator.clipboard.writeText(t);b.textContent='Copiado'}catch(e){b.textContent='Seleccioná el código para copiarlo'}}
function demoDiscount(){var r=activeSpin();if(!r)return 0;var prices=cart.filter(function(l){return !isPre(byId(l.id))}).map(function(l){return byId(l.id).precio});return prices.length?Math.round(Math.min.apply(null,prices)*PRIZES[r.prize].discount/100):0}
function checkoutGame(){var r=activeSpin();return r?'<div class="game-checkout"><b>Tu resultado de la ruleta: '+PRIZES[r.prize].label+'</b><p>Simulación: '+money(demoDiscount())+' sobre una camiseta en stock. El código '+esc(r.code)+' es de prueba y no modifica el importe a pagar.</p></div>':''}


var SPIN_INTERVAL=3*24*60*60*1000;
var gameClock=null,celebrationFrame=null,spinFrame=null,audioContext=null;
var soundEnabled=(function(){try{return localStorage.getItem('laonce-sonido')!=='off'}catch(e){return true}})();
function nextSpinLabel(){var r=activeSpin();if(!r)return 'Girar la ruleta ↗';var minutes=Math.max(1,Math.ceil((r.at+SPIN_INTERVAL-Date.now())/60000)),hours=Math.floor(minutes/60);return 'Volvés a girar en '+(hours?hours+' h ':'')+(minutes%60)+' min'}
function armGameClock(){clearTimeout(gameClock);if(activeSpin()&&!spinBusy)gameClock=setTimeout(function(){if(view==='game')renderGame()},Math.min(60000,Math.max(100,spinRecord.at+SPIN_INTERVAL-Date.now()+50)))}
function prepareSound(){if(!soundEnabled)return;try{var Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audioContext=audioContext||new Audio();if(audioContext.state==='suspended')audioContext.resume().catch(function(){})}catch(e){}}
function tone(frequency,start,length,volume,type){if(!soundEnabled||!audioContext||audioContext.state!=='running')return;try{var oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime+start;oscillator.type=type||'sine';oscillator.frequency.setValueAtTime(frequency,t);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(volume,t+.012);gain.gain.exponentialRampToValueAtTime(.0001,t+length);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(t);oscillator.stop(t+length+.03)}catch(e){}}
function victorySound(jackpot){if(document.hidden||view!=='game')return;[523.25,659.25,783.99,jackpot?1046.5:880].forEach(function(f,i){tone(f,i*.105,.4,.07,'triangle')});tone(261.63,.31,.65,.05);tone(523.25,.42,.55,.05)}
function toggleSound(){soundEnabled=!soundEnabled;try{localStorage.setItem('laonce-sonido',soundEnabled?'on':'off')}catch(e){}if(soundEnabled){prepareSound();tone(659,0,.16,.04)}var b=document.getElementById('toggleGameSound');if(b){b.textContent=soundEnabled?'♫ Sonido activado':'♫ Sonido desactivado';b.setAttribute('aria-pressed',String(soundEnabled))}}
function burstConfetti(jackpot){if(matchMedia('(prefers-reduced-motion: reduce)').matches||document.hidden)return;var old=document.getElementById('prizeConfetti');if(old)old.remove();cancelAnimationFrame(celebrationFrame);var cv=document.createElement('canvas');cv.id='prizeConfetti';cv.setAttribute('aria-hidden','true');document.body.appendChild(cv);var w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio||1,2);cv.width=w*dpr;cv.height=h*dpr;var ctx=cv.getContext('2d');if(!ctx){cv.remove();return}ctx.scale(dpr,dpr);var colors=['#eabc4e','#f3e8ce','#3c918a','#69b9ec','#ec7962'],particles=[];for(var i=0;i<(jackpot?190:120);i++){var side=i%2?1:-1;particles.push({x:side===1?w:0,y:h*.65,vx:-side*(100+Math.random()*520),vy:-260-Math.random()*600,r:Math.random()*6.28,vr:(Math.random()-.5)*12,size:5+Math.random()*7,color:colors[i%colors.length]})}var begin=performance.now(),last=begin;function frame(now){var dt=Math.min((now-last)/1000,.04),age=(now-begin)/1000;last=now;if(age>3.8||view!=='game'||document.hidden){cv.remove();return}ctx.clearRect(0,0,w,h);ctx.globalAlpha=Math.min(1,(3.8-age)/.8);particles.forEach(function(p){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=440*dt;p.vx*=Math.pow(.96,dt*60);p.r+=p.vr*dt;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillStyle=p.color;ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size*.5);ctx.restore()});celebrationFrame=requestAnimationFrame(frame)}celebrationFrame=requestAnimationFrame(frame)}
function celebratePrize(index){var surface=document.querySelector('.club-surface'),ticket=document.querySelector('.prize-ticket'),area=document.querySelector('.wheel-area');if(surface)surface.classList.add('celebrating');if(index===5&&surface)surface.classList.add('jackpot');if(ticket){ticket.classList.add('prize-reveal');if(innerWidth<=720)ticket.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'})}if(area)area.classList.add('winner');burstConfetti(index===5);victorySound(index===5)}
function spinWheel(){if(spinBusy||activeSpin())return;prepareSound();var index=choosePrize(randomTicket());spinRecord={prize:index,at:Date.now(),code:'DEMO-'+Date.now().toString(36).toUpperCase()};try{localStorage.setItem('laonce-ruleta-demo',JSON.stringify(spinRecord))}catch(e){}spinBusy=true;spinTurn=0;var btn=app.querySelector('#spinWheel');btn.disabled=true;btn.textContent='Girando…';clearTimeout(gameClock);cancelAnimationFrame(spinFrame);var reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,duration=reduced?100:5400,target=2520-index*60,start=performance.now(),lastSector=-1;function frame(now){var t=Math.min(1,(now-start)/duration);spinTurn=target*(1-Math.pow(1-t,4));var wheel=app.querySelector('.wheel-disc');if(wheel&&view==='game'){wheel.style.transition='none';wheel.style.transform='rotate('+spinTurn+'deg)';var sector=Math.floor((spinTurn+30)/60);if(sector!==lastSector&&!reduced&&!document.hidden){lastSector=sector;tone(900,0,.035,.015,'triangle');var pointer=app.querySelector('.wheel-pointer');if(pointer&&pointer.animate)pointer.animate([{transform:'rotate(-12deg)'},{transform:'rotate(0deg)'}],{duration:90})}}if(t<1){spinFrame=requestAnimationFrame(frame);return}spinBusy=false;spinFrame=null;if(view==='game'){renderGame();celebratePrize(index)}}spinFrame=requestAnimationFrame(frame)}
