/* Ruleta de demostración. Todas las recompensas tienen una probabilidad positiva. */
var PRIZES=[{label:'$3.000 OFF',short:'$3.000',weight:5900,discount:0,monto:3000},{label:'$6.000 OFF',short:'$6.000',weight:2500,discount:0,monto:6000},{label:'15% OFF',short:'15%',weight:1000,discount:15},{label:'25% OFF',short:'25%',weight:350,discount:25},{label:'Envío gratis',short:'ENVÍO',weight:150,discount:0,envio:true},{label:'Una camiseta gratis',short:'CAMISETA',weight:100,discount:100}];
var spinBusy=false,spinTurn=0,spinTimeout=null;
var spinRecord=loadSpin();
function loadSpin(){try{var v=JSON.parse(localStorage.getItem('laonce-ruleta-demo')||'null');return v&&Number.isInteger(v.prize)&&v.prize>=0&&v.prize<6&&Number.isFinite(v.at)&&v.at<=Date.now()&&typeof v.code==='string'&&/^(DEMO|ONCE)-[A-Z0-9-]+$/.test(v.code)?v:null}catch(e){return null}}
function activeSpin(){return spinRecord&&Date.now()-spinRecord.at<SPIN_INTERVAL?spinRecord:null}
function choosePrize(n){var sum=0;for(var i=0;i<PRIZES.length;i++){sum+=PRIZES[i].weight;if(n<sum)return i}throw Error('Sorteo fuera de rango')}
function randomTicket(){var a=new Uint32Array(1),max=Math.floor(4294967296/10000)*10000;do{crypto.getRandomValues(a)}while(a[0]>=max);return a[0]%10000}
function prizeTicket(){var r=activeSpin();if(!r||spinBusy)return '';var p=PRIZES[r.prize];if(r.used)return '<div class="prize-ticket" role="status"><span class="eyebrow">Tu premio</span><h2>'+p.label+'</h2><p>Ya lo usaste en tu último pedido. Volvés a girar cuando se cumplan los 3 días.</p></div>';return '<div class="prize-ticket" role="status"><span class="eyebrow">Tu premio</span><h2>'+p.label+'</h2><p>'+(p.envio?'Para tu próximo pedido con envío a domicilio.':p.monto?'Se descuenta de tu compra de camisetas en stock.':p.discount===100?'Una camiseta en stock gratis, la de menor precio de tu carrito. Envío aparte.':'Sobre una camiseta en stock, la de menor precio de tu carrito.')+' Se aplica solo al finalizar la compra.'+'</p><span class="coupon-code">'+esc(r.code)+'</span><button id="copyPrize">Copiar</button><p>Vence '+new Date(r.at+SPIN_INTERVAL).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})+''+(p.envio||p.monto?'. Se suma al descuento por transferencia.':'. No se suma al descuento por transferencia: te queda el mayor.')+'</p></div>'}
function gameRules(){return '<details class="game-rules"><summary>Premios, probabilidades y cómo funciona</summary><div class="odds">'+PRIZES.map(function(p){return '<div><strong>'+p.short+'</strong><span>'+(p.weight/100).toLocaleString('es-AR')+'% de probabilidad</span></div>'}).join('')+'</div><div class="rules-copy"><p>Las porciones de la rueda son ilustrativas: las probabilidades son las indicadas arriba y suman 100%. Todos los premios pueden salir.</p><p>Podés girar una vez cada 3 días. Tu premio dura 3 días desde que girás y queda guardado aunque cierres la página.</p><p>Los premios de $3.000 y $6.000 se descuentan de una compra con camisetas en stock y se suman al descuento por transferencia. Los porcentajes y la camiseta gratis se aplican sobre una camiseta en stock (la de menor precio del carrito), sin compra mínima; personalización aparte, y no se acumulan con el descuento por transferencia: se aplica el mayor beneficio. Los encargos no participan. El envío gratis vale para un pedido con envío a domicilio, incluidos los encargos, y sí se suma al descuento por transferencia.</p><p>El premio queda guardado en este navegador y se aplica automáticamente en el carrito y al finalizar la compra. Lo validamos con su código cuando coordinamos el pedido por WhatsApp. Un premio por pedido.</p></div></details>'}
function renderGame(){clearInterval(timer);var r=activeSpin();app.innerHTML=header()+'<main class="wrap club-main"><section class="club-surface"><div class="club-topline"><span>LA ONCE / EL RECREO</span><span class="club-demo">CADA 3 DÍAS</span></div><div class="club-layout"><div class="club-copy"><span class="eyebrow">El próximo gol puede ser tuyo</span><h1>Una vuelta.<br><em>Una ilusión.</em></h1><p>De $3.000 de descuento a una camiseta gratis. Dale un giro a la suerte.</p>'+prizeTicket()+'<button class="spin-button" id="spinWheel" '+(spinBusy||r?'disabled':'')+'>'+(spinBusy?'Girando…':r?nextSpinLabel():'Girar la ruleta ↗')+'</button>'+(r&&!r.used?'<button class="linkish" style="display:block;margin:14px auto 0" data-nav="stock">Usar mi premio en camisetas en stock →</button>':'')+'<button class="game-sound" id="toggleGameSound" aria-pressed="'+soundEnabled+'">'+(soundEnabled?'♫ Sonido activado':'♫ Sonido desactivado')+'</button><p class="spin-small">Un giro cada 3 días. Participación gratuita. El premio se aplica solo en tu carrito.</p></div><div class="wheel-area"><span class="wheel-pointer" aria-hidden="true"></span><div class="wheel-rim"><div class="wheel-disc" aria-hidden="true" style="transform:rotate('+(spinBusy?spinTurn:r?-r.prize*60:0)+'deg)">'+PRIZES.map(function(p,i){return '<div class="wheel-label'+(p.envio||p.monto?' wl-word':'')+'" style="--angle:'+(i*60)+'deg">'+p.short+'<small>'+(i===5||p.envio?'GRATIS':'DESCUENTO')+'</small></div>'}).join('')+'</div><span class="wheel-hub" aria-hidden="true">11</span></div></div></div><div class="club-bottom"><span>6 premios · Todas las chances a la vista</span><span>Sin compra obligatoria</span></div></section>'+gameRules()+'</main>'+footer()+'<dialog id="dlg"></dialog><dialog id="bagDlg" class="drawer"></dialog><div class="toast" id="toast" role="status"></div>';app.querySelector('#spinWheel').onclick=spinWheel;var b=app.querySelector('#copyPrize');if(b)b.onclick=function(){copyText(activeSpin().code,b)};app.querySelector('#toggleGameSound').onclick=toggleSound;armGameClock()}
async function copyText(t,b){try{await navigator.clipboard.writeText(t);b.textContent='Copiado'}catch(e){b.textContent='Seleccioná el código para copiarlo'}}
function prizeCalc(){var r=activeSpin();if(!r||r.used)return null;var P=PRIZES[r.prize];if(P.envio)return {r:r,P:P,disc:0,prod:null,envio:true};var st=cart.map(function(l){return byId(l.id)}).filter(function(p){return p&&!isPre(p)});if(!st.length)return {r:r,P:P,disc:0,prod:null};var p=st.reduce(function(a,b){return b.precio<a.precio?b:a});return P.monto?{r:r,P:P,disc:Math.min(P.monto,p.precio),prod:p,stack:true}:{r:r,P:P,disc:Math.round(p.precio*P.discount/100),prod:p}}
function demoDiscount(){var z=prizeCalc();return z?z.disc:0}
function prizeLabel(z){return z.P.discount===100?'Camiseta gratis':z.P.label}
function prizeLeft(r){var m=Math.max(1,Math.ceil((r.at+SPIN_INTERVAL-Date.now())/60000)),h=Math.floor(m/60);return (h?h+' h ':'')+(m%60)+' min'}
function checkoutGame(){var T=coTotals(),z=T.pz;if(!z)return '';var msg;if(z.envio)msg=T.envioPrize?'Tu envío a domicilio es gratis. Se suma al descuento por transferencia.':co.entrega==='envio'?'Tu pedido ya tiene envío gratis, así que tu premio queda guardado hasta que venza.':'Tu premio es envío gratis: se usa si elegís envío a domicilio.';else if(!z.disc)msg='Tu premio ('+esc(z.P.label)+') vale para compras con camisetas en stock. Los encargos no participan.';else if(z.stack)msg='Aplicamos '+esc(z.P.label)+' en tu compra'+(T.td?' y se suma al '+T.d+'% por transferencia.':'.');else if(T.usePrize)msg='Aplicamos '+(z.P.discount===100?'una camiseta gratis':esc(z.P.label))+' en '+esc(z.prod.club)+(T.td?'. No se suma al '+T.d+'% por transferencia: te dejamos el mayor beneficio.':'.');else msg='Con transferencia ya tenés '+T.d+'% en todo el pedido, que es igual o mejor que tu premio ('+esc(z.P.label)+'). Te aplicamos la transferencia y tu premio queda guardado hasta que venza.';return '<div class="game-checkout"><b>Premio de la ruleta</b><p>'+msg+'</p><p class="hint">Código '+esc(z.r.code)+' · vence en '+prizeLeft(z.r)+'</p></div>'}
function prizeBar(){if(view==='game')return '';var r=activeSpin();if(!r||r.used)return '';var P=PRIZES[r.prize];return '<button class="prize-bar" id="prizeBar" type="button"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 11h16v9H4zM3 7h18v4H3zM12 7v13M12 7c-1.5-3.5-6-3.5-5 0 .4 1.2 2.8 1 5 0zm0 0c1.5-3.5 6-3.5 5 0-.4 1.2-2.8 1-5 0z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg><span class="pb-txt">Ganaste <b>'+(P.discount===100?'una camiseta gratis':P.envio?'envío gratis':esc(P.label))+'</b> en la ruleta<span class="pb-sep"> · </span><span class="pb-when">vence en <b class="pb-time">'+prizeLeft(r)+'</b></span></span><span class="pb-go">Usar ›</span></button>'}
setInterval(function(){var el=document.querySelector('.pb-time');if(!el)return;var r=activeSpin();if(!r){render();return}el.textContent=prizeLeft(r)},30000);

/* Catálogo seleccionado: importación local revisable, no sincronización remota. */
var importDraft=[];
function supplierPanel(){return '<section class="admin-import"><h3>Catálogo por pedido</h3><p>Primera selección consultada el 29/09/2026. Fichas públicas de GRKITS, ASJSY y SSDAYS; no es disponibilidad en tiempo real. Los precios en pesos son de prueba. Descargá la copia HTML para conservar cambios.</p><p>Para ampliar: pegá un JSON con id, club, titulo, categoria, epoca, precio, fuente, foto y tallesPedido. Cada importación se revisa antes de incorporarla. Solo camisetas; sin shorts, conjuntos ni accesorios.</p><textarea id="importJson" aria-label="Catálogo JSON de camisetas" placeholder="Pegá acá el catálogo JSON seleccionado"></textarea><button class="btn btn-ghost" id="previewImport">Revisar importación</button><button class="btn btn-ghost" id="exportCatalog">Exportar catálogo por pedido</button><div id="importPreview" role="status"></div></section>'}
function cleanImported(rows){if(!Array.isArray(rows)||!rows.length||rows.length>500)throw Error('Usá una lista de entre 1 y 500 camisetas.');var seen=new Set();return rows.map(function(p,i){if(!p||typeof p!=='object')throw Error('Fila '+(i+1)+': formato inválido.');var id=String(p.id||'').trim();if(!/^[a-zA-Z0-9_-]{1,70}$/.test(id)||seen.has(id))throw Error('Fila '+(i+1)+': ID inválido o repetido.');seen.add(id);if(data.productos.some(function(x){return x.id===id&&!isPre(x)}))throw Error(id+': ese ID pertenece al stock local.');if(!p.club||!p.titulo||!CATS.includes(p.categoria)||!EPOCAS.includes(p.epoca))throw Error(id+': revisá club, título, categoría y época.');if(/\b(shorts?|pants|tracksuit|socks?|conjunto|pantal[oó]n|medias|nba|rugby)\b/i.test(p.titulo))throw Error(id+': la selección admite únicamente camisetas de fútbol.');if(!Number.isFinite(p.precio)||p.precio<=0)throw Error(id+': falta un precio positivo en pesos.');var url;try{url=new URL(p.fuente)}catch(e){throw Error(id+': falta el enlace de origen.')}var host=url.hostname.replace(/^www\./,'');if(url.protocol!=='https:'||url.username||url.password||!['grkits7.com','asjsy.com','ssdays2.com'].includes(host))throw Error(id+': usá un enlace HTTPS de uno de tus tres proveedores.');var sizes=Array.isArray(p.tallesPedido)?p.tallesPedido:[];if(!sizes.length||sizes.some(function(s){return !SIZES.includes(s)}))throw Error(id+': indicá tallesPedido con S, M, L, XL o XXL.');var photo=String(p.foto||'');if(photo&&!/^https:\/\//i.test(photo)&&!/^data:image\/(png|jpeg|webp);base64,[a-zA-Z0-9+/=]+$/.test(photo))throw Error(id+': formato de foto no admitido.');return {id:id,club:String(p.club).slice(0,100),titulo:String(p.titulo).slice(0,180),categoria:p.categoria,epoca:p.epoca,precio:Math.round(p.precio),precioAnterior:0,fuente:url.href,proveedor:host,fechaConsulta:p.fechaConsulta||new Date().toISOString().slice(0,10),foto:photo||null,tallesPedido:[...new Set(sizes)],stock:{S:0,M:0,L:0,XL:0,XXL:0},modalidad:'pedido',activo:p.activo!==false,patron:{tipo:'liso',c1:'#ddd',c2:'#aaa'},nuevo:false,destacado:false}})}
function previewImport(){var box=document.getElementById('importPreview');try{importDraft=cleanImported(JSON.parse(document.getElementById('importJson').value));box.innerHTML='<p>'+importDraft.length+' camisetas válidas. Elegí cuáles incorporar; los IDs existentes se actualizan.</p>'+importDraft.map(function(p,i){return '<label style="display:block;margin:8px 0"><input type="checkbox" data-import-row="'+i+'" checked> '+esc(p.club+' · '+p.titulo)+' · '+money(p.precio)+'</label>'}).join('')+'<button class="btn btn-ink" id="commitImport">Importar seleccionadas</button>'}catch(e){importDraft=[];box.innerHTML='<p class="import-error">'+esc(e.message)+'</p>'}}
function commitImport(){var selected=[...app.querySelectorAll('[data-import-row]:checked')].map(function(el){return importDraft[+el.dataset.importRow]});if(!selected.length){toast('Seleccioná al menos una camiseta');return}selected.forEach(function(p){var i=data.productos.findIndex(function(x){return x.id===p.id});if(i<0)data.productos.push(p);else data.productos[i]=p});dirty=true;adminMsg={kind:'info',text:selected.length+' camisetas incorporadas. Descargá la copia HTML para guardar.'};importDraft=[];renderAdmin()}
function exportCatalog(){var rows=data.productos.filter(isPre),blob=new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='La-ONCE-catalogo-por-pedido.json';a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000)}

var SPIN_INTERVAL=3*24*60*60*1000;
var gameClock=null,celebrationFrame=null,spinFrame=null,audioContext=null;
var soundEnabled=(function(){try{return localStorage.getItem('laonce-sonido')!=='off'}catch(e){return true}})();
function nextSpinLabel(){var r=activeSpin();if(!r)return 'Girar la ruleta ↗';var minutes=Math.max(1,Math.ceil((r.at+SPIN_INTERVAL-Date.now())/60000)),hours=Math.floor(minutes/60);return 'Volvés a girar en '+(hours?hours+' h ':'')+(minutes%60)+' min'}
function armGameClock(){clearTimeout(gameClock);if(activeSpin()&&!spinBusy)gameClock=setTimeout(function(){if(view==='game')renderGame()},Math.min(60000,Math.max(100,spinRecord.at+SPIN_INTERVAL-Date.now()+50)))}
function prepareSound(){if(!soundEnabled)return;try{var Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audioContext=audioContext||new Audio();if(audioContext.state==='suspended')audioContext.resume().catch(function(){})}catch(e){}}
function tone(frequency,start,length,volume,type){if(!soundEnabled||!audioContext||audioContext.state!=='running')return;try{var oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime+start;oscillator.type=type||'sine';oscillator.frequency.setValueAtTime(frequency,t);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(volume,t+.012);gain.gain.exponentialRampToValueAtTime(.0001,t+length);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(t);oscillator.stop(t+length+.03)}catch(e){}}
function victorySound(jackpot){if(document.hidden||view!=='game')return;[523.25,659.25,783.99,jackpot?1046.5:880].forEach(function(f,i){tone(f,i*.105,.4,.07,'triangle')});tone(261.63,.31,.65,.05);tone(523.25,.42,.55,.05)}
function toggleSound(){soundEnabled=!soundEnabled;try{localStorage.setItem('laonce-sonido',soundEnabled?'on':'off')}catch(e){}if(soundEnabled){prepareSound();tone(659,0,.16,.04)}var b=document.getElementById('toggleGameSound');if(b){b.textContent=soundEnabled?'♫ Sonido activado':'♫ Sonido desactivado';b.setAttribute('aria-pressed',String(soundEnabled))}}
function burstConfetti(jackpot){if(matchMedia('(prefers-reduced-motion: reduce)').matches||document.hidden)return;var old=document.getElementById('prizeConfetti');if(old)old.remove();cancelAnimationFrame(celebrationFrame);var cv=document.createElement('canvas');cv.id='prizeConfetti';cv.setAttribute('aria-hidden','true');document.body.appendChild(cv);var w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio||1,2);cv.width=w*dpr;cv.height=h*dpr;var ctx=cv.getContext('2d');if(!ctx){cv.remove();return}ctx.scale(dpr,dpr);var colors=['#eabc4e','#f3e8ce','#3c918a','#69b9ec','#ec7962'],particles=[];for(var i=0;i<(jackpot?190:120);i++){var side=i%2?1:-1;particles.push({x:side===1?w:0,y:h*.65,vx:-side*(100+Math.random()*520),vy:-260-Math.random()*600,r:Math.random()*6.28,vr:(Math.random()-.5)*12,size:5+Math.random()*7,color:colors[i%colors.length]})}var begin=performance.now(),last=begin;function frame(now){var dt=Math.min((now-last)/1000,.04),age=(now-begin)/1000;last=now;if(age>3.8||view!=='game'||document.hidden){cv.remove();return}ctx.clearRect(0,0,w,h);ctx.globalAlpha=Math.min(1,(3.8-age)/.8);particles.forEach(function(p){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=440*dt;p.vx*=Math.pow(.96,dt*60);p.r+=p.vr*dt;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillStyle=p.color;ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size*.5);ctx.restore()});celebrationFrame=requestAnimationFrame(frame)}celebrationFrame=requestAnimationFrame(frame)}
function celebratePrize(index){var surface=document.querySelector('.club-surface'),ticket=document.querySelector('.prize-ticket'),area=document.querySelector('.wheel-area');if(surface)surface.classList.add('celebrating');if(index===5&&surface)surface.classList.add('jackpot');if(ticket){ticket.classList.add('prize-reveal');if(innerWidth<=720)ticket.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'})}if(area)area.classList.add('winner');burstConfetti(index===5);victorySound(index===5)}
function spinWheel(){if(spinBusy||activeSpin())return;prepareSound();var index=choosePrize(randomTicket());spinRecord={prize:index,at:Date.now(),code:'ONCE-'+Date.now().toString(36).toUpperCase()};try{localStorage.setItem('laonce-ruleta-demo',JSON.stringify(spinRecord))}catch(e){}spinBusy=true;spinTurn=0;var btn=app.querySelector('#spinWheel');btn.disabled=true;btn.textContent='Girando…';clearTimeout(gameClock);cancelAnimationFrame(spinFrame);var reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,duration=reduced?100:5400,target=2520-index*60,start=performance.now(),lastSector=-1;function frame(now){var t=Math.min(1,(now-start)/duration);spinTurn=target*(1-Math.pow(1-t,4));var wheel=app.querySelector('.wheel-disc');if(wheel&&view==='game'){wheel.style.transition='none';wheel.style.transform='rotate('+spinTurn+'deg)';var sector=Math.floor((spinTurn+30)/60);if(sector!==lastSector&&!reduced&&!document.hidden){lastSector=sector;tone(900,0,.035,.015,'triangle');var pointer=app.querySelector('.wheel-pointer');if(pointer&&pointer.animate)pointer.animate([{transform:'rotate(-12deg)'},{transform:'rotate(0deg)'}],{duration:90})}}if(t<1){spinFrame=requestAnimationFrame(frame);return}spinBusy=false;spinFrame=null;if(view==='game'){renderGame();celebratePrize(index)}}spinFrame=requestAnimationFrame(frame)}
